BlueRunnerTestSolution/Controllers/NewsListController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json.Linq;
using PagedList;
using Models.Models;
using Services.Services;

namespace BlueRunnerTestSolution.Controllers
{
    public class NewsListController : Controller
    {
        private readonly IServices<Article> _articleService;
        private int pageSize = 6;

        public NewsListController(IServices<Article> articleService)
        {
            _articleService = articleService;
        }
        public NewsListController() { }
        // GET: NewsList
        public ActionResult Index(string searchStr, int? page)
        {
               
            ViewBag.Title = "Title";
            ViewBag.Section = "Section";
            ViewBag.TrailText = "Trail-Text";
            ViewBag.CurrentSearch = searchStr;

            List<Article> data = new List<Article>();

            //string searchStr = string.Empty;

            data = _articleService.GetList(searchStr);
            
            int pageNumber = page ?? 1;

            return View(data.ToPagedList(pageNumber, this.pageSize));
        }
    }
}

BlueRunnerTestSolution/Views/NewsList/Index.cshtml
@model PagedList.IPagedList<Models.Models.Article>
@using PagedList.Mvc

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
@using (Html.BeginForm("Index", "NewsList", FormMethod.Get))
{
    <div class="form-group">
        <div class="col-xs-4">
            @Html.TextBox("searchStr", ViewBag.CurrentSearch as string, new { @id = "searchString", @class = "form-control" })
        </div>
        <div class="col-xs-4">
            <input type="submit" class="btn btn-info" value="Search" />
        </div>
    </div>
}

@if (Model.Any())
{
    <table class="table table-striped">
        <tr>
            <th>
                Title
            </th>
            <th>
                Section
            </th>
            <th>
                Trail-Text
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr onclick="Redirect('@item.WebURL');" onmouseover="this.style.cursor='pointer'">
                <td>
                    @Html.DisplayFor(modelItem => item.WebTitle)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SectionId)/@Html.DisplayFor(modelItem => item.SectionName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
            </tr>
        }

    </table>
}


<br />
<br />

Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page , searchStr = ViewBag.CurrentSearch}))


<script src="~/Scripts/NewsList/NewsListScripts.js"></script>

BlueRunnerTestSolution/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>